#!/usr/bin/env bash

# Zram para ArchLinux
# Autor:
# Hector Ivan Vega Zamudio
# mxhectorvega@gmail.com
# https://github.com/mxhectorvega
# Version:
# v3.5: 12/12/2021


# Dotfiles Zram
clear
printf '\n \nClonando repositorios mxhectorvega...\n'
sleep 1
git clone https://github.com/mxhectorvega/zram-arch /tmp/zram-arch
sudo cp /tmp/zram-arch/zram-config-on /usr/local/bin/
sudo cp /tmp/zram-arch/zram-config-off /usr/local/bin/
sudo cp /tmp/zram-arch/zram-config.service /etc/systemd/system/
sudo chmod +x /usr/local/bin/zram-config-on
sudo chmod +x /usr/local/bin/zram-config-off
sudo systemctl enable --now zram-config

# Texto final
clear
printf '\n \nConfiguraciones aplicadas!'
sleep 1
printf '\n \nReincie para aplicar los cambios.'
sleep 1
printf '\n \nContribuye paypal.me/hivz'
sleep 1
printf '\n \n'
